### ISSUE TITLE
latest Mac "Intel" download is actually "ARM/AppleSilicon"

### ISSUE THREAD

**Issue by core-code** [beaufortfrancois/download-chromium#101]
https://download-chromium.appspot.com/?platform=Mac&type=snapshots

this now serves an ARM-only binary that cannot be launched on Intel Macs since about a few minutes ago. it was fine before.

**Comment by just-some-old-guy** [comment]
Indeed, can no longer get a new build of Chromium for my Intel iMac running Ventura.  Please fix this.

**Comment by Bo98** [comment]
Seems like there isn't an Intel build anymore since https://github.com/chromium/chromium/commit/da4bbeb2ee9c95faa8897df2293b06206b9e1519. Not sure if it's intentional or not.

You can find the last Intel build at: https://commondatastorage.googleapis.com/chromium-browser-snapshots/Mac/1307477/chrome-mac.zip

**Comment by beaufortfrancois** [comment]
Thanks for raising this issue!

I've pinged people involved in https://chromium-review.googlesource.com/c/chromium/src/+/5551672 to see if they can fix that.

**Comment by aelnosu** [comment]
The bug was submitted at: https://issues.chromium.org/issues/343505112

**Comment by aelnosu** [comment]
This issue has been resolved in the latest build.

**Comment by core-code** [comment]
thanks, confirmed
